version: '3.3'

services:
  fisherman-companion:
    build: .
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://containers-us-west-152.railway.app:6725/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 3s1PHTkdA6LRTN2ZBp0E
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGELOG: classpath:/db.changelog/changelog-master.yaml